title: "[Thema]: "
labels: ["themenvorschlag"]
body:
  - type: textarea
    id: beschreibung
    attributes:
      label: "📝 Beschreibung"
      description: "Beschreibe kurz das Thema, Ziel oder den Nutzen..."
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: "🎬 Formate"
      description: "Wähle die Formate"
      multiple: true
      options:
        - "⚡️ Lightning"
        - "🎤 Talk"
        - "🧪 Demo"
        - "🛠 Workshop"
        - "💬 Discussion"
      default: 3
  - type: input
    id: praesentiert_von
    attributes:
      label: "🎤 Präsentiert von"
      placeholder: "@username / oder zu bestimmen"
  - type: input
    id: dauer
    attributes:
      label: "⏱️ Dauer"
      placeholder: "<10 Minuten"
  - type: dropdown
    id: status
    attributes:
      label: "📌 Status"
      options:
        - "Vorschlag"
        - "In Planung"
        - "Nächstes Meetup"
        - "Behandelt"
      default: 0
